################################################################################################
#
# Shotgun Pipeline Toolkit Default VFX Configuration
#

# this file defines paths to key applications for this project


#
# maya
#
maya_windows: 'C:\Program Files\Autodesk\maya2013.5\bin\maya.exe'
maya_mac: /Applications/Autodesk/maya2013.5/Maya.app
maya_linux: maya


#
# nuke
#
nuke_mac: /Applications/Nuke7.0v6/Nuke7.0.app
nuke_windows: 'C:\Program Files\Nuke7.0v6\Nuke7.0.exe'
nuke_linux: Nuke7.0


#
# motionbuilder
#
motionbuilder_windows: 'C:\Program Files\Autodesk\MotionBuilder 2013\bin\x64\motionbuilder.exe'


#
# 3dsmax 2012
#
3dsmax_windows: 'C:\Program Files\Autodesk\3ds Max 2012\3dsmax.exe'


#
# Houdini
#
houdini_windows: 'C:\Program Files\Side Effects Software\Houdini 12.5.427\bin\houdini.exe'
houdini_linux: '/opt/hfs12.5.427/bin/houdini'


#
# photoshop CS6
#
photoshop_mac: /Applications/Adobe Photoshop CS6/Adobe Photoshop CS6.app
photoshop_win: 'C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe'
photoshop_extras:         
    mac_extension_manager_path: /Applications/Adobe Extension Manager CS6/Adobe Extension Manager CS6.app
    mac_python_path: /usr/bin/python
    windows_extension_manager_path: 'C:\Program Files (x86)\Adobe\Adobe Extension Manager CS6\XManCommand.exe'
    windows_python_path:  'T:\software\python27\python.exe'


#
# Hiero
#
hiero_mac: /Applications/Hiero1.7v2/Hiero1.7v2.app
hiero_win: C:\Program Files\The Foundry\Hiero1.7v2\hiero.exe
hiero_linux: /usr/local/Hiero1.7v2/bin/Hiero1.7v2

#
# Softimage
#

softimage_windows: C:\Program Files\Autodesk\Softimage 2013\Application\bin\XSI.bat
softimage_linux: XSI

#
# Tweak RV
#
rv_mac: /Applications/RV64.app
rv_win: C:\Program Files\RV\RV64.exe
rv_linux: rv

