default_proxy_apps:
  tk-multi-about:
    location: {name: tk-multi-about, type: app_store, version: v0.1.19}
  tk-multi-screeningroom: '@launch_screeningroom'
  tk-multi-workfiles:
    allow_task_creation: true
    file_extensions: []
    hook_copy_file: default
    hook_filter_publishes: default
    hook_filter_work_files: default
    hook_scene_operation: default
    launch_at_startup: false
    launch_change_work_area_at_startup: false
    location: {name: tk-multi-workfiles, type: app_store, version: v0.5.5}
    saveas_default_name: scene
    saveas_prefer_version_up: false
    sg_entity_type_extra_display_fields: {}
    sg_entity_type_filters: {}
    sg_entity_types: [Shot, Asset]
    task_extra_display_fields: []
    template_publish: null
    template_publish_area: null
    template_work: null
    template_work_area: null
  tk-multi-loader2-FULL_LOADER:
    action_mappings:
      Maya Scene: [open, open_work_file, audio, assemblyReference, reference, import, texture_node,
        importENV, loadSurfVar, coreArchive]
      Photoshop Image: [texture_node]
      Rendered Image: [texture_node]
    actions_hook: '{config}/tk-maya_actions.py'
    download_thumbnails: true
    entities:
    - caption: Assets
      entity_type: Asset
      filters:
      - [project, is, '{context.project}']
      hierarchy: [sg_asset_type, code]
    - caption: Shots
      entity_type: Shot
      filters:
      - [project, is, '{context.project}']
      hierarchy: [sg_sequence, code]
    - caption: Audio
      entity_type: CustomEntity03
      filters:
      - [project, is, '{context.project}']
      hierarchy: [sg_sequence_1, code]
    - caption: My Tasks
      entity_type: Task
      filters:
      - [task_assignees, is, '{context.user}']
      - [project, is, '{context.project}']
      hierarchy: [entity, content]
    filter_publishes_hook: '{self}/filter_publishes.py'
    location: {name: tk-multi-loader2, type: app_store, version: v1.2.1}
    menu_name: 0. Full Loader 2.0
    publish_filters: []
    shotPublishPathTemplate: maya_shot_publish
    shotWorkPathTemplate: maya_shot_work
    assetPublishPathTemplate: maya_asset_publish
    assetWorkPathTemplate: maya_asset_work
    title_name: File Loader 2.0
frameworks:
  tk-framework-qtwidgets_v1.x.x:
    location: {name: tk-framework-qtwidgets, type: app_store, version: v1.0.0}
  tk-framework-shotgunutils_v2.x.x:
    location: {name: tk-framework-shotgunutils, type: app_store, version: v2.0.4}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.17:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.17}
  tk-framework-widget_v0.1.20:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.20}
  tk-framework-widget_v0.1.23:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.23}
  tk-framework-widget_v0.1.24:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.24}
  tk-framework-widget_v0.2.x:
    location: {name: tk-framework-widget, type: app_store, version: v0.2.0}
include: ./app_launchers.yml
