description: Apps and Engines related to Asset based work.
engines:
  tk-maya:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.19}
      tk-multi-loader2:
        action_mappings:
          Maya Scene: [open, open_work_file, assemblyReference, reference, import, texture_node, coreArchive,
            importENV, importDGSHD]
          Photoshop Image: [texture_node]
          Rendered Image: [texture_node]
        actions_hook: '{self}/tk-maya_actions.py'
        download_thumbnails: true
        entities:
        - caption: Assets
          entity_type: Asset
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_asset_type, code]
        - caption: Shots
          entity_type: Shot
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_sequence, code]
        - caption: Audio
          entity_type: CustomEntity03
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_sequence_1, code]
        - caption: My Tasks
          entity_type: Task
          filters:
          - [task_assignees, is, '{context.user}']
          - [project, is, '{context.project}']
          hierarchy: [entity, content]
        filter_publishes_hook: '{self}/filter_publishes.py'
        location: {name: tk-multi-loader2, type: app_store, version: v1.2.1}
        menu_name: 0. Full Loader 2.0
        publish_filters: []
        title_name: File Loader 2.0
      tk-multi-publish-Audio:
        allow_taskless_publishes: true
        display_name: Publish Audio
        expand_single_items: false
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: maya_audio_primary_pre_publish
        hook_primary_publish: default
        hook_scan_scene: maya_audio_scan_scene
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.4.4}
        primary_description: Publish and version up the current Maya scene
        primary_display_name: Publish Audio
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_audio_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Scene
        secondary_outputs: []
        template_work: maya_audio_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-setframerange:
        location: {name: tk-multi-setframerange, type: app_store, version: v0.2.2}
        sg_in_frame_field: sg_cut_in
        sg_out_frame_field: sg_cut_out
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.2.14}
        template_snapshot: maya_audio_snapshot
        template_work: maya_audio_work
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.5.5}
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_extra_display_fields: {}
        sg_entity_type_filters: {}
        sg_entity_types: [Shot, Asset, CustomEntity03]
        task_extra_display_fields: []
        template_publish: maya_audio_publish
        template_publish_area: audio_publish_area_maya
        template_work: maya_audio_work
        template_work_area: audio_work_area_maya
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.4.2}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Shotgun Save As...}
    - {app_instance: tk-multi-publish, name: Publish...}
    template_project: audio_work_area_maya
    use_sgtk_as_menu_name: false
frameworks:
  tk-framework-qtwidgets_v1.x.x:
    location: {name: tk-framework-qtwidgets, type: app_store, version: v1.0.0}
  tk-framework-shotgunutils_v2.x.x:
    location: {name: tk-framework-shotgunutils, type: app_store, version: v2.0.4}
  tk-framework-widget_v0.1.1:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.1}
  tk-framework-widget_v0.1.10:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.10}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.16:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.16}
  tk-framework-widget_v0.1.17:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.17}
  tk-framework-widget_v0.1.18:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.18}
  tk-framework-widget_v0.1.19:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.19}
  tk-framework-widget_v0.1.20:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.20}
  tk-framework-widget_v0.1.23:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.23}
  tk-framework-widget_v0.1.24:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.24}
  tk-framework-widget_v0.1.3:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.3}
  tk-framework-widget_v0.1.4:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.4}
  tk-framework-widget_v0.1.5:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.5}
  tk-framework-widget_v0.2.x:
    location: {name: tk-framework-widget, type: app_store, version: v0.2.0}
include: ./includes/app_launchers.yml
